In [1]:
%cd ..
from src.data import load
from src.features import build_features

df = load()
X, y, step, amount = build_features(df)
X.head()

/Users/lakshyashetty/Projects/fraud-detection

,log_amount,is_transfer,hour,is_night,round_amount,dest_prev_count,dest_prev_mean,amount_vs_dest_mean,steps_since_dest_last,orig_prev_count
0,5.204007,1,1,1,0,0,0.0,181.00,-1.0,0
1,5.204007,0,1,1,0,0,0.0,181.00,-1.0,0
2,12.342066,0,1,1,0,0,0.0,229133.94,-1.0,0
3,12.279840,1,1,1,0,0,0.0,215310.30,-1.0,0
4,12.649754,1,1,1,0,0,0.0,311685.89,-1.0,0

In [2]:
X.assign(isFraud=y).groupby("isFraud").mean().T

isFraud                            0             1
log_amount                 11.924932  1.289203e+01
is_transfer                 0.191446  4.988433e-01
hour                       15.319966  1.154645e+01
is_night                    0.009438  2.430293e-01
round_amount                0.001080  3.689273e-02
dest_prev_count             5.301681  1.772190e+00
dest_prev_mean         247186.535774  8.562848e+04
amount_vs_dest_mean     51077.301717  1.001613e+06
steps_since_dest_last      30.018869  3.539851e+01
orig_prev_count             0.000642  1.217582e-03